/*
 * OpenHiker - Offline Hiking Navigation
 * Copyright (C) 2024 - 2026 Dr Horst Herb
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package com.openhiker.core.model

import kotlinx.serialization.Serializable

/**
 * A single turn-by-turn navigation instruction at a junction.
 *
 * Generated by the routing engine's TurnDetector from the computed edge
 * sequence. Used by the RouteFollower during live navigation to determine
 * when to alert the user about upcoming turns.
 *
 * @property coordinate The geographic location of this junction.
 * @property direction The type of turn (left, right, straight, etc.).
 * @property bearing Outgoing bearing in degrees (0–360, clockwise from north).
 * @property distanceFromPrevious Distance in metres from the previous instruction.
 * @property cumulativeDistance Distance in metres from the route start.
 * @property trailName Name of the trail/road from the OSM `name` tag, or null.
 * @property description Human-readable instruction (e.g., "Turn left onto Blue Ridge Trail").
 */
@Serializable
data class TurnInstruction(
    val coordinate: Coordinate,
    val direction: TurnDirection,
    val bearing: Double,
    val distanceFromPrevious: Double,
    val cumulativeDistance: Double,
    val trailName: String? = null,
    val description: String
) {
    /**
     * Unique identifier for this instruction, derived from location and distance.
     *
     * Matches the iOS format: "{lat},{lon},{cumulativeDistance}" for
     * cross-platform instruction matching in shared route files.
     */
    val id: String
        get() = "${coordinate.latitude},${coordinate.longitude},$cumulativeDistance"
}
